name: nexus_store_workspace
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  lints: ^5.0.0
  melos: ^6.2.0
  test_reporter:
    git:
      url: https://github.com/unfazed-dev/test_reporter.git
      ref: main
