name: nexus_store_flutter
description: Flutter extension for nexus_store with StreamBuilder widgets and providers.
version: 0.1.0
repository: https://github.com/user/nexus_store

environment:
  sdk: ^3.5.0
  flutter: ">=3.22.0"


dependencies:
  flutter:
    sdk: flutter
  nexus_store: ^0.1.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
